from datetime import datetime, timezone, timedelta
from typing import Dict, Any
from pydantic import BaseModel, Field

class DataFlag(BaseModel):
    """Represents an active warning flag generated by pipeline issues"""
    flag_type: str = Field(..., description="The category of pipeline failure")
    source: str = Field(..., description="The original data source causing the warning")
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)

def is_data_fresh(last_updated: datetime) -> bool:
    """Returns True if the data was updated within the last 24 hours, False otherwise"""
    if not last_updated:
        return False
    
    now = datetime.now(timezone.utc)
    if last_updated.tzinfo is None:
        last_updated = last_updated.replace(tzinfo=timezone.utc)

    return (now - last_updated) <= timedelta(hours=24)

def check_confidence_threshold(score: float) -> Dict[str, Any]:
    """Evaluates a model score and returns a status dict with flags for low confidence"""
    is_low = score < 0.75
    return {
        "score": score,
        "low_confidence_flag": is_low,
        "action": "flag_for_review" if is_low else "approve"
    }

def generate_ingestion_flag(source: str, error_message: str) -> DataFlag:
    """Generates a structured DataFlag object for source ingestion failures"""
    return DataFlag(
        flag_type="INGESTION_FAILURE",
        source=source,
        metadata={"error": error_message}
    )
