"""add_feedback_table

Revision ID: 7a59dd209592
Revises: ac19895e7528
Create Date: 2026-08-20 18:49:47.607818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7a59dd209592'
down_revision: Union[str, Sequence[str], None] = 'ac19895e7528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morning_note_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('buy', 'sell', 'keep')", name='ck_feedback_action'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['morning_note_id'], ['morning_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_manager_id'), 'feedbacks', ['manager_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_morning_note_id'), 'feedbacks', ['morning_note_id'], unique=False)

    # Enable RLS and create policy for manager isolation
    op.execute("ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY feedbacks_manager_isolation "
        "ON feedbacks "
        "USING (manager_id = current_setting('app.manager_id', true)::int) "
        "WITH CHECK (manager_id = current_setting('app.manager_id', true)::int)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS feedbacks_manager_isolation ON feedbacks")
    op.execute("ALTER TABLE feedbacks DISABLE ROW LEVEL SECURITY")
    op.drop_index(op.f('ix_feedbacks_morning_note_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_manager_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
